version: '3'

services:
  mysqldev:
    container_name: mysqldev
    image: "mysql:latest"
    ports:
    - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=unitconversion
      - MYSQL_USER=sadmin
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    
  unitconversion:
    image: unitconversion-image
    container_name: unitconversion
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      mysqldev:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: sadmin
      SPRING_DATASOURCE_PASSWORD: password  
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldev:3306/unitconversion
    volumes:
      - ./data/spring-boot-app
